Section "ServerFlags"
    # 禁用屏幕休眠（产品需常亮显示）
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection

Section "Device"
    Identifier  "HDMI"
    Driver      "modesetting"
    Option      "AccelMethod" "glamor"
    Option      "DRI" "3"
EndSection
